### PR TITLE
Update compendium.md

### PR DESCRIPTION
**Pull request by 7048730**
suggestion for spatial MD

### CODE REVIEW

**Comment by nuest** [comment]
To get the overall bounding box (I'm not sure "master" is a good name... mayb  "union"?) I have to loop through all elements of the arrays. Or will the items in the array have to be ordered?

What about using the file names as names for objects?

```
metadata.spatial.union.geojson
metadata.spatial["shapefile.shp"]
```

**Comment by 7048730** [comment]
That's right. I saw this and do agree it would be nice to have `metadata.spatial.union` as direct key. The counter argument would be that not all subkeys are equal then.

Perhaps:

```
spatial
+ union
+ files [ 
...
]
```

As for the filenames:  I had this at first but changed it because filenames could be all identical like "shape.shp" from different paths (sub dirs). Other identifiers might be uuids, md5(fullpath), counter, timestamp or ordered list without id.

**Comment by 7048730** [comment]
I have a strong disfavor for non-alphanumeric object names. they tend to cause trouble. anyway we can do this, if all agree.

**Comment by nuest** [comment]
Yeah, I see that those names could complicate development.
So I'm OK with the updated suggestion: use `geojson` and `source` at the same level within each object in the array `files`.

**Comment by 7048730** [comment]
fine. I will update the text once the extractor can do this.

**Comment by nuest** [comment]
Example compendium metadata with spatial information (need to provid this to study project as they want to work on spatial badges):

```json
{
   "id":"comid",
   "metadata":{
      "spatial":{
         "union":{
            "bbox":[
               7.595369517803192,
               51.96245837645124,
               7.62162297964096,
               51.96966694957956
            ],
            "geometry":{
               "coordinates":[
                  [
                     [
                        7.595369517803192,
                        51.96245837645124
                     ],
                     [
                        7.62162297964096,
                        51.96966694957956
                     ]
                  ]
               ],
               "type":"Polygon"
            },
            "files":[
               {
                  "geojson":{
                     "bbox":[
                        7.595369517803192,
                        51.96245837645124,
                        7.62162297964096,
                        51.96966694957956
                     ],
                     "geometry":{
                        "coordinates":[
                           [
                              [
                                 7.595369517803192,
                                 51.96245837645124
                              ],
                              [
                                 7.62162297964096,
                                 51.96966694957956
                              ]
                           ]
                        ],
                        "type":"Polygon"
                     },
                     "type":"Feature"
                  },
                  "source":"rasterdata/geo.tiff"
               },
               {
                  "geojson":{
                     "bbox":[
                        7.595369517803192,
                        51.96245837645124,
                        7.62162297964096,
                        51.96966694957956
                     ],
                     "geometry":{
                        "coordinates":[
                           [
                              [
                                 7.595369517803192,
                                 51.96245837645124
                              ],
                              [
                                 7.62162297964096,
                                 51.96966694957956
                              ]
                           ]
                        ],
                        "type":"Polygon"
                     },
                     "type":"Feature"
                  },
                  "source":"example/layers/POLYGON.shp"
               }
            ]
         }
      },
      "created":"2016-08-01T13:57:40.760Z",
      "files":{

      }
   }
}
```

**Comment by nuest** [comment]
@7048730 can you merge with the current master so this PR has no conflicts?

**Comment by 7048730** [comment]
@nuest 
> These conflicts are too complex to resolve with the web editor.

But isn't it a complete replacement anyway?

**Comment by 7048730** [comment]
I looked it over again, fixed the formatting and I think we can merge this for now.
However there are several parts that seem outdated again, since this PR is so old.
I suggest, we update it again in the near future to match the erc spec. But I'd like to do this with a new clean PR.

**Comment by nuest** [comment]
The structure changed, the file that was originally changed does not exist anymore. I made the merge now.

**Comment by nuest** [comment]
@7048730 What did you fix? I don't see the commit yet.

**Comment by 7048730** [comment]
@nuest it's gone. I fixed the ill formatted json structure. though my commit was displayed for a short time, your merge seems to have obsoleted it.

**Pull request merged**
